WebUI/Areas/Dashboard/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebUI.Utilities;
using WebUI.Entities;
using WebUI.Manager;
using WebUI.Areas.Dashboard.ViewModels;

namespace WebUI.Areas.Dashboard.Controllers
{
    public class PedidoController : AdminBaseController
    {
        public ActionResult Recibidos()
        {
            IEnumerable<Pedido> listaPedidos = PedidoManager.GetRecibidos(usuario.Id);
            return View(listaPedidos);
        }

        public ActionResult Enviados()
        {
            IEnumerable<Pedido> listaPedidos = PedidoManager.GetEnviados(usuario.Id);
            return View(listaPedidos);
        }

        [HttpPost]
        public ActionResult Pedido(int IdPedido)
        {
            Pedido pedido = PedidoManager.GetPedido(usuario.Id, IdPedido);
            if (pedido.Visto == "novisto")
            {
                PedidoManager.SetVisto(IdPedido);
            }

            PedidoViewModel pedidoVM = new PedidoViewModel()
            {
                IdPedido = pedido.IdPedido,
                Arbol = pedido.Arbol,
                Emisor = pedido.Emisor,
                Receptor = pedido.Receptor,
                Oferta = pedido.Oferta,
                Fecha = pedido.Fecha
            };

            string vistaParcial = "";
            if (usuario.Id == pedidoVM.Emisor.Id)
            {
                vistaParcial = "_Enviado";
            }
            else
            {
                switch (pedido.Estado)
                {
                    case "Pendiente": vistaParcial = "_Pendiente";break;
                    case "Aceptado": vistaParcial = "_Aceptado"; break;
                    case "Rechazado": vistaParcial = "_Rechazado"; break;
                    default: break;
                }
            }

            return PartialView("~/Areas/Dashboard/Views/Pedido/" + vistaParcial + ".cshtml", pedidoVM);
        }

        [HttpPost]
        public ActionResult Rechazar(int idPedido)
        {
            PedidoManager.Rechazar(idPedido);
            return Json(new WebUI.Models.AjaxResponseViewModel { Success = true, Message = "Pedido rechazado" }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult Aceptar(int idPedido)
        {
            PedidoManager.Aceptar(idPedido);
            Pedido pedido = PedidoManager.GetPedido(idPedido);
            PedidoViewModel pedidoVM = new PedidoViewModel
            {
                IdPedido = pedido.IdPedido,
                Arbol = pedido.Arbol,
                Emisor = pedido.Emisor,
                Receptor = pedido.Receptor,
                Oferta = pedido.Oferta,
                Fecha = pedido.Fecha
            };
            return PartialView("~/Areas/Dashboard/Views/Pedido/_Aceptado.cshtml", pedidoVM);
        }

        [HttpPost]
        public void Eliminar(int idPedido, String visible)
        {
            PedidoManager.Eliminar(idPedido,visible);
        }
    }
}

WebUI/Controllers/AltaUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Manager;
using WebUI.ViewModels;
using WebUI.Entities;

namespace WebUI.Controllers
{
    public class AltaUsuarioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(CuentaNuevaViewModel model)
        {
            Boolean existeError = false;
            if (!UsuarioManager.EmailUnico(model.Email))
            {
                ModelState.AddModelError("Email", "El email ya fue utilizado.");
                existeError = true;
            }
            if (!UsuarioManager.NombreUsuarioUnico(model.NombreUsuario))
            {
                existeError = true;
                ModelState.AddModelError("NombreUsuario", "El nombre de usuario ya existe.");
            }
            if (existeError)
            {
                return View(model);
            }
            Usuario usuario = new Usuario
            {
                       Nombre = model.Nombre,
                NombreUsuario = model.NombreUsuario,
                        Email = model.Email,
                         Pass = model.Pass
            };

            UsuarioManager.Nuevo(usuario);
            TempData["Msg"] = "Su árbol fue modificado correctamente";
            return View("CuentaCreada",usuario);
        }
    }
}
//TODO: modificar columnas en BD para que nombreusuario y mail sean únicos

WebUI/Controllers/BuscadorController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebUI.Entities;
using WebUI.Manager;
using WebUI.Utilities;
using WebUI.ViewModels;

namespace WebUI.Controllers
{
    public class BuscadorController : Controller
    {
        public ActionResult Buscar(BuscarViewModel model)
        {
            int? IdUsuario = null;
            if (Session[Constantes.KeyCurrentUser] != null)
            {
                Usuario usuario = (Usuario)Session[Constantes.KeyCurrentUser];
                IdUsuario = usuario.Id;
            }
            ViewBag.Variedad = model.Variedad;
            ViewBag.Titulo = "Resultados de búsqueda";
            List<Arbol> arbols = ArbolManager.GetArbolesByVariedad(model.Variedad, IdUsuario);
            //armar array de destinos
            String destinos = "";
            foreach (var arbol in arbols)
            {
                destinos += arbol.Latitud + ", " + arbol.Longitud + "|";
            }
            //pasarlo al manager
            JObject arrayDistancias = ArbolManager.CalcularDistancia(model.Posicion, destinos);
            //armar el viewmodel y agregar la ditancia
            List<ResultadosViewModel> arboles = new List<ResultadosViewModel>();
            for (int i = 0; i < arbols.Count; i++)
            {
                arboles.Add(
                    new ResultadosViewModel
                    {
                        Id = arbols[i].Id,
                        Variedad = arbols[i].Variedad,
                        Disponibilidad = arbols[i].Disponibilidad,
                        Latitud = arbols[i].Latitud,
                        Longitud = arbols[i].Longitud,
                        Direccion = arbols[i].Direccion,
                        Distancia = arrayDistancias["rows"][0]["elements"][i]["distance"]["text"].ToString()
                    }
                );
        }
            //reordeno la lista con linq segun distancia
            var result = (from s in arboles
                         select s).OrderBy(x => x.Distancia);
            return View("Resultados", result);
        }

        public ActionResult Detalle(int id)
        {
            ViewBag.Titulo = "Detalle";
            Arbol arbol = ArbolManager.GetArbol(id);
            String destino = arbol.Latitud + ", " + arbol.Longitud;
            JObject arrayDistancias = ArbolManager.CalcularDistancia("-34.9314, -57.9489", destino);
            String distancia = arrayDistancias["rows"][0]["elements"][0]["distance"]["text"].ToString();
            List<ResultadosViewModel> arboles = new List<ResultadosViewModel>
            {
                new ResultadosViewModel
                {
                    Id = arbol.Id,
                    Variedad = arbol.Variedad,
                    Disponibilidad = arbol.Disponibilidad,
                    Direccion = arbol.Direccion,
                    Distancia = distancia
                }
            };
            return View("Resultados", arboles);
        }
    }
}

WebUI/Views/Shared/_ErrorSummary.cshtml
@Html.ValidationSummary(true, "", new { @class = "text-danger" })

WebUI/Views/Shared/_Layout.cshtml
@using WebUI.Utilities;
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid cuerpo">
        @{ Html.RenderAction("MostrarNavbar","Home"); }
        <div class="content">
            <article class="contenido-target">
                @RenderBody()
            </article>
        </div>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/app")
    @Scripts.Render("~/bundles/typeahead")
    @Scripts.Render("~/bundles/mapa")
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqGcfcsaTBLx40K7RoHgQTLnV05qX2mZI"></script>
    @if (Session[Constantes.KeyCurrentUser] == null)
    {
        @Scripts.Render("~/bundles/login")
        <script type="text/javascript">
            $(document).ready(function () {
                Buscador.focus();
                Login.init();
            });
        </script>
    }
    @RenderSection("scripts", required: false)       
</body>
</html>

WebUI/Views/Shared/_LayoutVacio.cshtml
@using WebUI.Utilities;
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <article class="contenido-target">
            @RenderBody()
        </article>
        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)

</body>
</html>

WebUI/Views/Shared/_ModalLogin.cshtml
@model WebUI.ViewModels.LoginViewModel
<div class="modal-dialog" role="document">
    <div class="modal-content miModal">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Iniciar sesión</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="containerLogin">
                @using (Ajax.BeginForm("Index", "Home", new AjaxOptions(){HttpMethod = "POST",OnSuccess = "Login.onSucces", UpdateTargetId = "ErrorSummary"},new{@class = "form-signin",role = "form"}))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <div id="ErrorSummary"></div>
                        <div class="form-group">
                            @Html.HiddenFor(model => model.id)
                            @Html.EditorFor(model => model.NombreUsuario, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre de usuario", autofocus = "" } })
                            @Html.ValidationMessageFor(model => model.NombreUsuario, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control", @placeholder = "Contraseña" } })
                            @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Ingresar" class="btn btn-info btn-block" />
                        </div>
                    </div>

                }
            <p>
                <a href="javascript:Login.mostrarRestaurarCuenta();" class="pull-right">¿Ha olvidado su contraseña?</a>
            </p>
            <p>
                @Html.ActionLink("Registrarse.", "Index", "AltaUsuario",null, new { @class = "" })
            </p>
            </div>
            <div class="sidebar-module" id="containerResetear" style="display:none;">
                <p>Ingrese su E-mail</p>
                @using (Html.BeginForm("Resetear", "Home", FormMethod.Post, new { @class = "form-signin", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.TextBox("Email", "", new { @class = "form-control", @placeholder = "Email", required = "required", type = "email" })
                        @Html.ValidationMessage("Email", "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <button class="btn btn-info btn-block" type="submit">Restaurar</button>
                    </div>
                    <p>
                        <a href="javascript:Login.mostrarLogin();" class="pull-right">Cancelar</a>
                    </p>
                }
            </div>
        </div>
    </div>
</div>

WebUI/Views/Shared/_Navbar.cshtml
@model WebUI.ViewModels.BuscarViewModel

@using WebUI.Utilities;
@using WebUI.Entities;
@{
    Usuario usuario = (Usuario)Session[Constantes.KeyCurrentUser];
}
<header>
    <nav class="navbar navbar-expand-md navbar-light container">
        @Html.ActionLink("Mandame Fruta", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar5">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar5">
            @using (Html.BeginForm("Buscar", "Buscador", FormMethod.Get, new { @class = "mx-2 my-auto d-inline w-100" }))
            {
                @Html.EditorFor(model => model.Posicion)
                <div class="input-group">
                    @Html.EditorFor(model => model.Variedad, new { htmlAttributes = new { @class = "form-control typeahead", id = "buscar", placeholder = "Buscar fruta", autocomplete = "off", required = "true", type = "search" } })
                    @Html.ValidationMessage("variedad", "", new { @class = "text-danger" })
                    <input type="submit" value="Buscar" class="btn btn-primary" />
                </div>
            }
            <ul class=" nav navbar-nav ml-auto mt-2 mt-lg-0">
                @if (Session[Constantes.KeyCurrentUser] == null)
                {
                    <li>
                        <a href="javascript:Login.mostrarModalLogin('@Url.Action("MostrarModalLogin","Home")');">
                            Ingresar
                        </a>
                    </li>
                }
                else
                {
                    <li class="nav-item dropdown ml-auto">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">@usuario.Nombre</a>
                        <div class="dropdown-menu" id="dropdown-user-menu">
                            @Html.ActionLink("Mi Perfil", "Detalle", "Usuario", new { area = "Dashboard" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Mis Árboles", "Lista", "Arbol", new { area = "Dashboard" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Mis Pedidos", "Recibidos", "Pedido", new { area = "Dashboard" }, new { @class = "dropdown-item" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("Cerrar sesión", "CerrarSesion", "Home", new { area = "" }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
            </ul>

        </div>
    </nav>
</header>